version: "3.1"

services:
  app:
    container_name: image-uploader-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
      - mongo-express
      - localstack
    environment:
      - TESTE=TESTE
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    networks:
      - server-network

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: uploaderdb
      MONGO_INITDB_DATABASE: imageUploader
    networks:
      - server-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: uploaderdb
      ME_CONFIG_MONGODB_URL: mongodb://root:uploaderdb@db:27017/
    networks:
      - server-network

  localstack:
    container_name: "localstack-img-uploader"
    image: localstack/localstack
    networks:
      - server-network
    ports:
      - "4566-4583:4566-4583"
    environment:
      - SERVICES=sqs,s3
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  server-network:
    driver: bridge
